---

- name: Copy optimizer server shell file
  copy:
    src: "init.sh"
    dest: "/root/init.sh"
    owner: root
    group: root
    mode: 0755
- name: Run optimizer server shell file
  shell: /root/init.sh
- name: "Build hosts file"
  lineinfile:
    path: "/etc/hosts"
    regexp: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}"
    line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}"
    state: present
    backup: yes
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"