---
- name: Install Docker container engine
  include_tasks: pkg.yml

- name: Create Docker config directory
  file:
    path: "/etc/docker/"
    state: directory

- name: Copy Docker config file
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"

- name: Create Docker config directory
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory

- name: Enable and check Docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_docker
