---
- name: Install Docker container engine
  shell: curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun

- name: Create Docker config directory
  file:
    path: "/etc/docker"
    state: directory

- name: Copy Docker engine service file
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"

- name: Create Docker service config directory
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory

- name: Enable and check Docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_docker
