---
- name: Install apt-transport-https
  when: ansible_os_family == "Debian"
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes

- name: Add Docker APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg

- name: Add Docker APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb http://mirrors.aliyun.com/docker-ce/linux/ubuntu bionic stable
    state: present
    filename: 'docker'

- name: ensure required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add docker ce repo
  shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  register: docker_yum_repo

- name: Install docker engine (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum:
    name: "docker-ce-{{ docker_version }}.*"
    state: present

- name: Install docker engine (Debian)
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: "docker-ce={{ docker_version }}*"
    state: present

- name: Hold docker version
  when: ansible_os_family == "Debian"
  dpkg_selections:
    name: docker-ce
    selection: hold
